manage HTML page with summary of compilation and test results

diff --git a/scripts/run-tests b/scripts/run-tests
--- a/scripts/run-tests
+++ b/scripts/run-tests
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 declare -ri	EC_ARG_ERROR=1
 declare -ri	EC_GIT_ERROR=10
@@ -24,24 +24,15 @@ declare		tests_repo_url='https://gitlab.psi.ch/OPAL/regression-tests.git'
 declare		arg_force_run='no'
 
 # default branch for OPAL sources and regression tests
-declare		arg_branch='master'
+declare		branch='master'
 
 # compile only
 declare		arg_compile_only='no'
 
 # absolute or relative directory where to publish the results
-# of the regression tests. If empty, nothing will be published.
+# of the regression und unit tests. If empty, nothing will be
+# published.
 declare -x	publish_dir=''
-
-# absolute or relative directory where to publish the results
-# of the unit tests. If empty, nothing will be published.
-declare 	publish_dir_unittests=''
-
-# relative  directory where to clone the Git source repository
-# if empty and 'publish_dir' is specified, use base-name of it
-# if neither is specified, use name of branch (which defaults
-# to master)
-declare -x	repo_dir=''
 
 # arguments passed to CMake
 declare -a	cmake_args=()
@@ -52,77 +43,90 @@ declare -a	opal_args=()
 # arguments passed to the regression test runner
 declare	-a opts=()
 
+# tests to run, all if non passed as argument
+declare -a tests=()
+
+# run unit- and/or regression tests
+declare opt_unittests='yes'
+declare opt_regtests='yes'
+
+# option/arguments passed to the unit-tests
+declare -a unittests_args=()
 while (( $# > 0 )); do
 	case $1 in
+                --branch|--branch=* )
+                        if [[ $1 == *=* ]]; then
+                                branch="${1#*=}"
+                        else
+                                branch="$2"; shift 1
+                        fi
+                        ;;
 		--compile-only )
 			arg_compile_only='yes'
 			;;
-		--cmake-args )
-			cmake_args+=( $2 )
-			shift 1
+		--cmake-args|--cmake-args=* )
+                        if [[ $1 == *=* ]]; then
+		                cmake_args+=( "${1#*=}" )
+                        else
+			        cmake_args+=( "$2" ); shift 1
+		        fi
+		        ;;
+		--opal-args|--opal-args=* )
+                        if [[ $1 == *=* ]]; then
+			        opal_args+=( "${1#*=}" )
+                        else
+			        opal_args+=( "$2" ); shift 1
+                        fi
 			;;
-		--cmake-args=* )
-			cmake_args+=( ${1#*=} )
-			;;
-		--opal-args )
-			opal_args+=("$2")
-			shift 1
-			;;
-		--opal-args=* )
-			opal_args+=("${1#*=}")
-			;;
-		--publish-dir )
-			publish_dir="$2"
-			shift 1
-			;;
-		--publish-dir=* )
-			publish_dir="${1#*=}"
-			;;
-		--publish-dir-unittests )
-			publish_dir_unittests="$2"
-			shift 1
-			;;
-		--publish-dir-unittests=* )
-			publish_dir_unittests="${1#*=}"
-			;;
-		--repo-dir )
-			repo_dir="$2"
-			shift 1
-			;;
-		--repo-dir=* )
-			repo_dir="${1#*=}"
-			;;
-		--src-repo-url )
-			src_repo_url="$2"
-			shift 1
-			;;
-		--src-repo-url=* )
-			src_repo_url="${1#*=}"
-			;;
-		--tests-repo-url )
-			tests_repo_url="$2"
-			shift 1
-			;;
-		--tests-repo-url=* )
-			tests_repo_url="${1#*=}"
-			;;
+		--publish-dir|--publish-dir=* )
+                        if [[ $1 == *=* ]]; then
+			        publish_dir="${1#*=}"
+                        else
+		                publish_dir="$2"; shift 1
+                        fi
+		        ;;
+		--src-repo-url|--src-repo-url=* )
+                        if [[ $1 == *=* ]]; then
+		                src_repo_url="${1#*=}"
+                        else
+		                src_repo_url="$2"; shift 1
+                        fi
+		        ;;
+		--tests-repo-url|--tests-repo-url=* )
+                        if [[ $1 == *=* ]]; then
+		                tests_repo_url="${1#*=}"
+                        else
+		                tests_repo_url="$2"; shift 1
+                        fi
+		        ;;
+                --reg-tests )
+                        opt_unittests='no'
+                        opt_regtests='yes'
+                        ;;
+                --unit-tests )
+                        opt_unittests='yes'
+                        opt_regtests='no'
+                        ;;
+                --unit-tests-args|--unit-tests-args=* )
+                        if [[ $1 == *=* ]]; then
+                                unittests_args+=( "${1#*=}" )
+                        else
+                                unittests_args+=( "$2" ); shift 1
+                        fi
+                        ;;
 		-f | --force )
-			arg_force_run='yes'
-			;;
+		        arg_force_run='yes'
+		                      ;;
 		-* )
-			echo "Unknown option: $1" 1>&2
-			exit
-			;;
+		        echo "Unknown option: $1" 1>&2
+		        exit
+		        ;;
 		* )
-			arg_branch="$1"
-			;;
+		        tests+=( "$1" )
+		        ;;
 	esac
 	shift 1
 done
-
-if [[ -z "${repo_dir}" ]]; then
-	repo_dir=${arg_branch}
-fi
 
 #.............................................................................
 # directory layout
@@ -141,7 +145,7 @@ declare -r abs_scriptname=$(readlink -f "$0")
 declare -r bindir="${abs_scriptname%/*}"
 declare -r prefix="${bindir%/*}"
 declare -r workspace="${prefix}/workspace"
-declare -r branchdir="${workspace}/${repo_dir}"
+declare -r branchdir="${workspace}/${branch}"
 declare -r srcdir="${branchdir}/src"
 declare    builddir="${branchdir}/build"
 declare -r testsbase="${branchdir}/tests"
@@ -151,13 +155,86 @@ declare -r confdir="${testsbase}/conf"
 declare -r keytab="${HOME}/.keytab"
 declare -r PRINCIPAL_NAME='svcusr-amas_regr@D.PSI.CH'
 
+declare -A result
+result['compile']='-'
+result['u_total']='-'
+result['u_passed']='-'
+result['u_failed']='-'
+result['u_disabled']='-'
+result['u_broken']='-'
+result['r_total']='-'
+result['r_passed']='-'
+result['r_failed']='-'
+result['r_disabled']='-'
+result['r_broken']='-'
+
+declare -r today=$(date +%Y-%m-%d)
+
+trap _exit EXIT
+
+
+_exit() {
+        local -i ec=$?
+
+        # nothing to do if no publication directory is defined
+        [[ -n ${publish_dir} ]] || return ${ec}
+
+        # org file with the table we have to update
+        local -r index_org="${publish_dir}/${branch}/index.org"
+
+        # copy template to target directory if not exist
+        if [[ ! -e "${index_org}" ]]; then
+	        cp -v \
+                   "${bindir}/html/index.org" \
+                   "${index_org}"
+        fi
+
+        # links to generated XML pages used in the table
+        local -r u_results_xml="../unitTests/${branch}/results_${today}.xml"
+        local -r r_results_xml="../regressionTests/${branch}/results_${today}.xml"
+
+        # build string with result for unit-tests. This will be used as link-name.
+        local -r u_t="totl:${result['u_total']}"
+        local -r u_p="pass:${result['u_passed']}"
+        local -r u_f="fail:${result['u_failed']}"
+        local -r u_d="skip:${result['u_disabled']}"
+        local -r u_b="brkn:${result['u_broken']}"
+        local -r u_report="${u_t}; ${u_p}; ${u_f}; ${u_d}; ${u_b}"
+
+        # build string with result for regression-tests. This will be used as link-name.
+        local -r r_t="totl:${result['r_total']}"
+        local -r r_p="pass:${result['r_passed']}"
+        local -r r_f="fail:${result['r_failed']}"
+        local -r r_d="skip:${result['r_disabled']}"
+        local -r r_b="brkn:${result['r_broken']}"
+        local -r r_report="${r_t}, ${r_p}, ${r_f}, ${r_d}, ${r_b}"
+
+        # add new line to org table
+        line=""
+        line+="| ${today} "
+        line+="| ${result['compile']} "
+        line+="| [[${u_results_xml}][${u_report}]] "
+        line+="| [[${r_results_xml}][${r_report}]] "
+        line+="|"
+        local -r tmpfile=$(mktemp "/tmp/awk.XXXXXX")
+        awk "{print}; /^\|---/ {print \"${line}\"}" \
+            ${index_org} > "${tmpfile}"
+        mv "${tmpfile}" "${index_org}"
+
+        emacs --batch --eval "
+                (with-current-buffer (find-file-noselect \"${index_org}\")
+                  (org-html-export-as-html)
+                  (write-file \"index.html\"))"
+
+}
+
 clone_repo() {
 	local -r repo_url="$1"
 	local -r dir="$2"
 	{
 		git clone "${repo_url}" "${dir}"|| exit ${EC_GIT_ERROR}
 		cd "${dir}"
-		git checkout "${arg_branch}" 	|| exit ${EC_GIT_ERROR}
+		git checkout "${branch}" 	|| exit ${EC_GIT_ERROR}
 	}
 }
 
@@ -181,77 +258,126 @@ update_repo() {
 	fi
 
 	local -r branch=$(git rev-parse --abbrev-ref HEAD)
-	if [[ "${branch}" != "${arg_branch}" ]]; then
-		git checkout "${arg_branch}" || exit 10
+	if [[ "${branch}" != "${branch}" ]]; then
+		git checkout "${branch}" || exit 10
 	fi
 	git fetch || { echo "git fetch failed!" 1>&2; exit 10; }
-	local -i num_changed_files=$(git diff --name-only  "origin/${arg_branch}"  | wc -l | awk '{print $1}')
+	local -i num_changed_files=$(git diff --name-only  "origin/${branch}"  | wc -l | awk '{print $1}')
 	if (( $num_changed_files == 0 )); then
 		echo "Working directory '${repodir}' is up to date!"
 		return 1
 	fi
-	git merge "origin/${arg_branch}" || { echo "git merge failed!" 1>&2; exit 11; };
+	git merge "origin/${branch}" || { echo "git merge failed!" 1>&2; exit 11; };
 	return 0
 }
 
 compile_opal() {
+        result['compile']='failed'
 	cd "${basedir}" 	|| exit 1
 	rm -rf "${builddir}"	|| exit 1
 	mkdir "${builddir}"	|| exit 1
 	cd "${builddir}"	|| exit 1
-	cmake "${cmake_args[@]}" "${srcdir}"
+	cmake "${cmake_args[@]}" "${srcdir}" || exit 1
 	time make -j5 || exit 1
+        result['compile']='ok'
 }
 
 run_unit_test() {
-	[[ -n "${publish_dir_unittests}" ]] || return 0
-	tests_bin="${builddir}/tests/opal_unit_tests"
-	[[ -x "${tests_bin}" ]] || return 0
+        # compile with unit-tests enabled?
+        local -r tests_bin="${builddir}/tests/opal_unit_tests"
+        [[ -x "${tests_bin}" ]] || return 0
 
-	mkdir -p "${publish_dir_unittests}"
-	local today=$(date +%Y-%m-%d)
-	local output_file="${publish_dir_unittests}/results_${today}".xml
-	${builddir}/tests/opal_unit_tests --gtest_output=xml:"${output_file}"
-	sed -n -i 'p;1a <?xml-stylesheet type="text/xsl" href="results.xsl"?>' "${output_file}" 
+        # run unit-test only if OPAL has been compiled
+        [[ ${result['compile']} == '-' ]] && return 0
 
-	local -i tests
-	local -i failures
-	local -i disabled
-	local -i errors
+        if [[ -n "${publish_dir}" ]]; then
+                local -r publish_unittests_dirs="${publish_dir}/unitTests/${branch}"
+                mkdir -p "${publish_unittests_dirs}"
+                local output_file="${publish_unittests_dirs}/results_${today}.xml"
+                unittests_args+=( "--gtest_output=xml:${output_file}" )
+        fi
 
-	eval $(awk '/<testsuites / {printf "%s %s %s %s\n", $2, $3, $4, $5}' "${output_file}")
+        ${tests_bin} "${unittests_args[@]}"
+        local -i ec=$?
 
-	test_overview="[ total: ${tests} "
-	test_overview+="| failures: ${failures} "
-	test_overview+="| disabled: ${disabled} "
-	test_overview+="| errors: ${errors} ] <br/>"
+        [[ -n ${publish_dir} ]] || return ${ec}
 
-	line="<a href=\"${output_file##*/}\">${today}</a> ${test_overview}"
+        # add stylesheet to output
+        sed -n -i 'p;1a <?xml-stylesheet type="text/xsl" href="results.xsl"?>' \
+            "${output_file}" 
 
-	if [[ ! -e "${publish_dir_unittests}/index.html" ]]; then
-		echo "<head>
+        local -i tests
+        local -i failures
+        local -i disabled
+        local -i errors
+
+        eval $(awk '/<testsuites / {printf "%s %s %s %s\n", $2, $3, $4, $5}' \
+                   "${output_file}")
+
+        test_overview="[ total: ${tests} "
+        test_overview+="| failures: ${failures} "
+        test_overview+="| disabled: ${disabled} "
+        test_overview+="| errors: ${errors} ] <br/>"
+
+        result['u_total']=${tests}
+        result['u_passed']=$((tests - failures - disabled - errors))
+        result['u_failed']=${failures}
+        result['u_disabled']=${disabled}
+        result['u_broken']=${errors}
+
+        line="<a href=\"${output_file##*/}\">${today}</a> ${test_overview}"
+
+        if [[ ! -e "${publish_unittests_dirs}/index.html" ]]; then
+	        echo "<head>
   <body>
   </body>
 </head>
-" > "${publish_dir_unittests}/index.html"
-	fi
-	if [[ ! -e "${publish_dir_unittests}/result.xsl" ]]; then
-		cp -v "${bindir}/html/gtest-result.xsl" "${publish_dir_unittests}/results.xsl"
-	fi
-	sed -i "/  <body>/a ${line}" "${publish_dir_unittests}/index.html"
+" > "${publish_unittests_dirs}/index.html"
+        fi
+        if [[ ! -e "${publish_unittests_dirs}/result.xsl" ]]; then
+	        cp -v \
+                   "${bindir}/html/gtest-result.xsl" \
+                   "${publish_unittests_dirs}/results.xsl"
+        fi
+        sed -i "/  <body>/a ${line}" "${publish_unittests_dirs}/index.html"
+        return ${ec}
 }
 
 run_regressiontests() {
-	if [[ -n "${publish_dir}" ]]; then
-		mkdir -p "${publish_dir}"
-		opts+=("--publish-dir=${publish_dir}")
-	fi
+        if [[ -n "${publish_dir}" ]]; then
+                local -r publish_regtests_dir="${publish_dir}/regressionTests/${branch}"
+	        mkdir -p "${publish_regtests_dir}"
+	        opts+=("--publish-dir=${publish_regtests_dir}")
+        fi
+
 	if [[ -n "${opal_args}" ]]; then
 		opts+=(${opal_args[@]/#/--opal-args=})
 	fi
 	opts+=("--opal-exe-path=${builddir}/src")
 	opts+=("--base-dir=${testsdir}")
+        
 	"${run_tests}" "${opts[@]}" "--" "${tests[@]}"
+        local -i ec=$?
+
+        [[ -n ${publish_dir} ]] || return ${ec}
+
+        # get results from HTML file created/updated by regression-tests 
+        local index_html="${publish_regtests_dir}/index.html"
+        read passed broken failed total < <(
+                awk "/${today}/ {
+                     split(\$3, p, \":\");
+                     split(\$5, b, \":\");
+                     split(\$7, f, \":\");
+                     split(\$9, t,  \":\");
+                     printf \"%s %s %s %s\n\", p[2], b[2], f[2], t[2]; exit}" \
+                             < ${index_html})
+        result['r_total']=${total/\]}
+        result['r_passed']=${passed}
+        result['r_failed']=${failed}
+        result['r_disabled']='-'
+        result['r_broken']=${broken}
+
+        return ${ec}
 }
 
 main() {
@@ -302,12 +428,14 @@ main() {
 			/usr/bin/kinit -t "${keytab}" -k "${PRINCIPAL_NAME}"	|| exit 2
 			/usr/bin/aklog						|| exit 2
 		fi
-
-		echo "Running unit tests..."
-		run_unit_test
-		echo "Running regression tests..."
-		run_regressiontests || exit 1
-
+                if [[ ${opt_unittests} == 'yes' ]]; then
+		        echo "Running unit tests..."
+		        run_unit_test
+                fi
+                if [[ ${opt_regtests} == 'yes' ]]; then
+		        echo "Running regression tests..."
+		        run_regressiontests || return 1
+                fi
 		if [[ -r "${keytab}" ]]; then
 			/usr/bin/unlog
 			/usr/bin/kdestroy
@@ -316,3 +444,10 @@ main() {
 }
 
 main
+
+# Local Variables:
+# mode:sh-mode
+# sh-basic-offset: 8
+# indent-tabs-mode: nil
+# require-final-newline: nil
+# End:
diff --git a/scripts/run-tests-macos-master b/scripts/run-tests-macos-master
--- a/scripts/run-tests-macos-master
+++ b/scripts/run-tests-macos-master
@@ -15,8 +15,9 @@
 usage() {
         echo "
 Usage:
-     ${basename $0} [--publish-dir=[DIR]] [REGRESSION_TESTS]
+     $()basename $0) [--publish-dir=[DIR]] [REGRESSION_TESTS]
 " 1>&2
+        exit 1
 }
 
 #-----------------------------------------------------------------------------
@@ -37,7 +38,8 @@ declare -r branch='master'
 # arguments passed to CMake
 #
 declare -a cmake_args=()
-cmake_args+=( "-DCMAKE_BUILD_TYPE=RELEASE" )
+#cmake_args+=( "-DCMAKE_BUILD_TYPE=RELEASE" )
+cmake_args+=( "-DCMAKE_BUILD_TYPE=DEBUG" )
 cmake_args+=( "-DBUILD_OPAL_UNIT_TESTS=TRUE" )
 cmake_args+=( "-DENABLE_SAAMG_SOLVER=TRUE" )
 
@@ -49,30 +51,12 @@ declare -a opal_args=()
 #..............................................................................
 # arguments passed to OPAL unit tests
 declare unittests_args=()
-unittests_args+=( '--gtest_filter=-GreenWakeFunctionTest.TestApply' )
+unittests_args+=( '--gtest_filter=-GreenWakeFunctionTest.TestApply:Field.PeriodicBC' )
 
 #..............................................................................
 # modules to load/setup build environment
 #
-source /opt/psi/config/profile.bash
-module purge
-module use unstable
-module load cmake/3.14.0
-module load gnuplot/5.2.7
-module load Python/3.6.3
 
-module load gcc/7.4.0
-module load gsl/2.6
-module load OpenBLAS/0.3.7
-module load gtest/1.8.1
-
-module load openmpi/3.1.4
-module load amrex/18.07_3d
-module load boost/1.70.0
-module load hdf5/1.10.5
-
-module load H5hut/2.0.0rc6
-module load trilinos/12.12.1
 #
 # end of configuration
 #-----------------------------------------------------------------------------
@@ -89,7 +73,8 @@ module load trilinos/12.12.1
 # results of unit-tests:
 #	${publish_dir}/unitTests/${branch} 	results of regression-tests
 #
-declare -r publish_dir='/afs/psi.ch/project/amas/webhosting/opal'
+declare    publish_dir='/afs/psi.ch/project/amas/webhosting/opal'
+declare -a opts=()
 declare -a tests=()
 
 while (( $# > 0 )); do
@@ -101,7 +86,11 @@ while (( $# > 0 )); do
                                 publish_dir=$2; shift
                         fi
                         ;;
+                --force|-f|--reg-tests|--unit-tests )
+                        opts+=( "$1" )
+                        ;;
                 -* )
+                        echo "Invalid option -- $1\n"
                         usage
                         ;;
                 * )
@@ -117,28 +106,24 @@ done
 declare -r src_repo_url='https://gitlab.psi.ch/OPAL/src.git'
 declare -r tests_repo_url='https://gitlab.psi.ch/OPAL/regression-tests.git'
 
-<
 #..............................................................................
 # prepend option names to CMake und OPAL arguments
 #
-declare -r cmake_args=( "${cmake_args[@]/#/--cmake-args=}" )
-declare -r opal_args=( "${opal_args[@]/#/--opal-args=}" )
-declare -r unittests_args=( "${unittests_args[@]/#/--unit-tests-args}" )
+opts+=( "${cmake_args[@]/#/--cmake-args=}" )
+opts+=( "${opal_args[@]/#/--opal-args=}" )
+opts+=( "${unittests_args[@]/#/--unit-tests-args=}" )
 
 #..............................................................................
 # here we go ...
 #
 declare -r bindir=$(dirname "$0")
-bash -x "${bindir}/run-tests"				\
-     --branch=${branch}                                 \
-     "${cmake_args[@]}"					\
-     "${opal_args[@]}"					\
-     "${unittests_args[@]}"                             \
-     --src-repo-url="${src_repo_url}"			\
-     --tests-repo-url="${tests_repo_url}"		\
-     --repo-dir=${branch}				\
-     --publish-dir="${publish_dir}" 			\
-     "$@"
+"${bindir}/run-tests"				\
+        --branch=${branch}                      \
+        --src-repo-url="${src_repo_url}"	\
+        --tests-repo-url="${tests_repo_url}"	\
+        --publish-dir="${publish_dir}" 		\
+        "${opts[@]}"                            \
+        "${tests[@]}"
 
 # Local Variables:
 # mode:sh-mode
